export const Actiontypes = {
  SEARCH_ITEM: 'SEARCH_ITEM',
  FETCH_SPECIFIC_PRODUCT: 'FETCH_SPECIFIC_PRODUCT',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCTS: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCT',
  WISH_LISTED_PRODUCT: 'WISH_LISTED_PRODUCT',
  MENS_PRODUCTS:"MENS_PRODUCTS",
  WOMENS_PRODUCT:"WOMENS_PRODUCTS",
  GROCERIES:"GROCERIES",
};
